require_relative 'leftovers/entities/users.rb'
require_relative 'leftovers/entities/foods.rb'
require_relative 'leftovers/entities/restaurants.rb'
require_relative 'leftovers/databases/database.rb'
require_relative 'leftovers/scripts/user_registration.rb'
require_relative 'leftovers/scripts/sign_in.rb'
require_relative 'leftovers/scripts/restaurant_registration.rb'
require_relative 'leftovers/scripts/geo_location_finder.rb'
